### ISSUE TITLE
 Object 'cvsd' not found

### ISSUE THREAD

**Issue by amb354909** [rauschenberger/joinet#1]
Hi,

I am running the following code from the joinet package examples:

n <- 50; p <- 100; q <- 3
X <- matrix(rnorm(n*p),nrow=n,ncol=p)
Y <- replicate(n=q,expr=rnorm(n=n,mean=rowSums(X[,1:5])))

joinet(Y=Y,X=X)

And I get the following error:

$base
$base$y1

Call:  NULL 

Error in cbind(optlams, which, cvm[which], cvsd[which], nzero[which]) : 
  object 'cvsd' not found

I think I have installed all necessary packages, and am still getting the error. Thank you for your time.

**Comment by rauschenberger** [comment]
Thanks for opening this issue. I am sorry for overlooking it. Objects `cvsd`, `nzero` and `lambda.1se` are not needed for the base learners. I replaced them with`NA` so that calling `glmnet::print.cv.glmnet` does not return an error.
